//! TypeScript client generation.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::sync::Arc;

use crate::action::{ErasedAction, ErasedStreamAction};

/// Emits a `<name>Params` / `<name>Result` (unary) or `<name>Item` (stream) type
/// per action.
///
/// (v1: type definitions. A fuller typed client + `assert_ts_synced` come next.)
pub(crate) fn generate<G, R>(
    actions: &HashMap<&'static str, Arc<dyn ErasedAction<G, R>>>,
    streams: &HashMap<&'static str, Arc<dyn ErasedStreamAction<G, R>>>,
) -> String {
    let mut out = String::from("// Generated by stakit-router. Do not edit.\n\n");

    let mut unary: Vec<&&'static str> = actions.keys().collect();
    unary.sort_unstable();
    for name in unary {
        let action = &actions[*name];
        let _ = writeln!(out, "export type {name}Params = {};", action.input_ts());
        let _ = writeln!(out, "export type {name}Result = {};\n", action.output_ts());
    }

    let mut stream: Vec<&&'static str> = streams.keys().collect();
    stream.sort_unstable();
    for name in stream {
        let action = &streams[*name];
        let _ = writeln!(out, "export type {name}Params = {};", action.input_ts());
        let _ = writeln!(out, "export type {name}Item = {};\n", action.item_ts());
    }
    out
}
