//! TypeScript client generation.

use std::collections::{BTreeSet, HashMap};
use std::fmt::Write as _;
use std::sync::Arc;

use crate::action::{ErasedAction, ErasedStreamAction};

/// Emits each referenced model declaration once, followed by an action index
/// (`name: Params => Result` / `=> stream<Item>`).
pub(crate) fn generate<G, R>(
    actions: &HashMap<&'static str, Arc<dyn ErasedAction<G, R>>>,
    streams: &HashMap<&'static str, Arc<dyn ErasedStreamAction<G, R>>>,
) -> String {
    let mut out = String::from("// Generated by stakit-router. Do not edit.\n\n");
    let mut seen = BTreeSet::new();

    let mut unary: Vec<&'static str> = actions.keys().copied().collect();
    unary.sort_unstable();
    let mut stream: Vec<&'static str> = streams.keys().copied().collect();
    stream.sort_unstable();

    // 1. type declarations (deduped) — `export interface …` / `export type …`.
    for name in &unary {
        let action = &actions[*name];
        push_decl(&mut out, &mut seen, &action.input_ts());
        push_decl(&mut out, &mut seen, &action.output_ts());
    }
    for name in &stream {
        let action = &streams[*name];
        push_decl(&mut out, &mut seen, &action.input_ts());
        push_decl(&mut out, &mut seen, &action.item_ts());
    }

    // 2. action index (comments — the wire envelope is always `{status,data|error}`).
    out.push_str("// Actions (params => result):\n");
    for name in &unary {
        let action = &actions[*name];
        let _ = writeln!(
            out,
            "//   {name}: {} => {}",
            type_ref(&action.input_ts()),
            type_ref(&action.output_ts())
        );
    }
    for name in &stream {
        let action = &streams[*name];
        let _ = writeln!(
            out,
            "//   {name}: {} => stream<{}>",
            type_ref(&action.input_ts()),
            type_ref(&action.item_ts())
        );
    }
    out
}

/// Emits `ts` as a top-level declaration once (skips inline scalars).
fn push_decl(out: &mut String, seen: &mut BTreeSet<String>, ts: &str) {
    if ts.starts_with("export ") && seen.insert(ts.to_owned()) {
        out.push_str(ts);
        out.push_str("\n\n");
    }
}

/// The name to reference a type by: the declared name for a struct/enum, or the
/// inline type itself for scalars/collections (`"number"`, `"Array<string>"`).
fn type_ref(ts: &str) -> &str {
    let named = ts
        .strip_prefix("export interface ")
        .or_else(|| ts.strip_prefix("export type "));
    match named {
        Some(rest) => rest.split([' ', '<']).next().unwrap_or(ts),
        None => ts,
    }
}
