//! TypeScript client generation.
//!
//! Emits the referenced model declarations once, then typed maps a TS client
//! generic over `Router` can infer from: `ActionParameters`, `ActionResults`,
//! `ActionKinds`, `ClientActionParameters`, `ClientActionResults`.

use std::fmt::Write as _;
use std::sync::Arc;

use hashbrown::{HashMap, HashSet};

use crate::action::{ErasedAction, ErasedStreamAction};
use crate::client::ClientMeta;

pub(crate) fn generate<G, R>(
    actions: &HashMap<&'static str, Arc<dyn ErasedAction<G, R>>>,
    streams: &HashMap<&'static str, Arc<dyn ErasedStreamAction<G, R>>>,
    client_actions: &[ClientMeta],
) -> String {
    let mut out = String::from("// Generated by stakit-router. Do not edit.\n\n");
    let mut seen = HashSet::new();

    let mut unary: Vec<&'static str> = actions.keys().copied().collect();
    unary.sort_unstable();
    let mut stream: Vec<&'static str> = streams.keys().copied().collect();
    stream.sort_unstable();
    let mut clients: Vec<&ClientMeta> = client_actions.iter().collect();
    clients.sort_unstable_by_key(|c| c.name);

    // 1. deduped declarations.
    for name in &unary {
        push_decl(&mut out, &mut seen, &actions[*name].input_ts());
        push_decl(&mut out, &mut seen, &actions[*name].output_ts());
    }
    for name in &stream {
        push_decl(&mut out, &mut seen, &streams[*name].input_ts());
        push_decl(&mut out, &mut seen, &streams[*name].item_ts());
    }
    for c in &clients {
        push_decl(&mut out, &mut seen, &c.params_ts);
        push_decl(&mut out, &mut seen, &c.return_ts);
    }

    // 2. typed maps.
    out.push_str("export interface ActionParameters {\n");
    for name in &unary {
        let _ = writeln!(out, "  {name}: {};", type_ref(&actions[*name].input_ts()));
    }
    for name in &stream {
        let _ = writeln!(out, "  {name}: {};", type_ref(&streams[*name].input_ts()));
    }
    out.push_str("}\n\nexport interface ActionResults {\n");
    for name in &unary {
        let _ = writeln!(out, "  {name}: {};", type_ref(&actions[*name].output_ts()));
    }
    for name in &stream {
        let _ = writeln!(out, "  {name}: {};", type_ref(&streams[*name].item_ts()));
    }
    out.push_str("}\n\nexport interface ActionKinds {\n");
    for name in &unary {
        let _ = writeln!(out, "  {name}: \"unary\";");
    }
    for name in &stream {
        let _ = writeln!(out, "  {name}: \"stream\";");
    }
    out.push_str("}\n\nexport interface ClientActionParameters {\n");
    for c in &clients {
        let _ = writeln!(out, "  {}: {};", c.name, type_ref(&c.params_ts));
    }
    out.push_str("}\n\nexport interface ClientActionResults {\n");
    for c in &clients {
        let _ = writeln!(out, "  {}: {};", c.name, type_ref(&c.return_ts));
    }
    out.push_str("}\n\n");

    // 3. the single Router type a client infers from.
    out.push_str(concat!(
        "export interface Router {\n",
        "  serverActions: {\n",
        "    [K in keyof ActionParameters]: {\n",
        "      params: ActionParameters[K];\n",
        "      result: ActionResults[K];\n",
        "      kind: ActionKinds[K];\n",
        "    };\n",
        "  };\n",
        "  clientActions: {\n",
        "    [K in keyof ClientActionParameters]: {\n",
        "      params: ClientActionParameters[K];\n",
        "      return: ClientActionResults[K];\n",
        "    };\n",
        "  };\n",
        "}\n",
    ));
    out
}

/// Emits `ts` as a top-level declaration once (skips inline scalars).
fn push_decl(out: &mut String, seen: &mut HashSet<String>, ts: &str) {
    if ts.starts_with("export ") && seen.insert(ts.to_owned()) {
        out.push_str(ts);
        out.push_str("\n\n");
    }
}

/// The name to reference a type by: the declared name for a struct/enum, or the
/// inline type itself for scalars/collections (`"number"`, `"Array<string>"`).
fn type_ref(ts: &str) -> &str {
    ts.strip_prefix("export interface ")
        .or_else(|| ts.strip_prefix("export type "))
        .map_or(ts, |rest| rest.split([' ', '<']).next().unwrap_or(ts))
}
