// Generated by stakit-router. Do not edit.

export interface Greet {
  name: string;
  user_id?: number;
}

export interface Greeting {
  message: string;
}

export interface Count {
  n: number;
}

// Actions (params => result):
//   greet: Greet => Greeting
//   count: Count => stream<number>
