// Generated by stakit-router. Do not edit.

export interface Count {
  n: number;
}

export interface Greet {
  name: string;
  userId?: number;
}

export interface Greeting {
  message: string;
}

export interface SaveImage {
  fileName: string;
}

export interface Saved {
  bytes: number;
  path: string;
}

export interface Toast {
  text: string;
}

export interface ActionParameters {
  greet: Greet;
  notify: Greet;
  save_image: SaveImage;
  version: null;
  count: Count;
  progress: Count;
}

export interface ActionResults {
  greet: Greeting;
  notify: Greeting;
  save_image: Saved;
  version: string;
  count: number;
  progress: number;
}

export interface ActionKinds {
  greet: "unary";
  notify: "unary";
  save_image: "unary";
  version: "unary";
  count: "stream";
  progress: "stream";
}

export interface ClientActionParameters {
  showToast: Toast;
}

export interface ClientActionResults {
  showToast: string;
}

export interface Router {
  serverActions: {
    [K in keyof ActionParameters]: {
      params: ActionParameters[K];
      result: ActionResults[K];
      kind: ActionKinds[K];
    };
  };
  clientActions: {
    [K in keyof ClientActionParameters]: {
      params: ClientActionParameters[K];
      return: ClientActionResults[K];
    };
  };
}
